version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/debuggers-backend/

permissions:
  - object: /home/ubuntu/debuggers-backend/
    pattern: '**'
    owner: ubuntu
    group: ubuntu
    mode: 755
    type:
      - directory
      - file
  - object: /home/ubuntu/debuggers-backend/scripts/
    pattern: '**'
    owner: ubuntu
    group: ubuntu
    mode: 755
    type:
      - directory
      - file

hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start_application.sh
      timeout: 300
      runas: ubuntu
  ApplicationStop:
    - location: scripts/stop_application.sh
      timeout: 300
      runas: ubuntu
